"""add vocabularylist and vocabularywords model and api router

Revision ID: 880b83a291cf
Revises: 6bded65e32a7
Create Date: 2025-11-28 11:46:26.862609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880b83a291cf'
down_revision: Union[str, Sequence[str], None] = '6bded65e32a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_lists_id'), 'vocabulary_lists', ['id'], unique=False)
    op.create_table('vocabulary_list_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['vocabulary_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_list_words_id'), 'vocabulary_list_words', ['id'], unique=False)
    op.create_index('ix_vocabulary_list_words_list', 'vocabulary_list_words', ['list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vocabulary_list_words_list', table_name='vocabulary_list_words')
    op.drop_index(op.f('ix_vocabulary_list_words_id'), table_name='vocabulary_list_words')
    op.drop_table('vocabulary_list_words')
    op.drop_index(op.f('ix_vocabulary_lists_id'), table_name='vocabulary_lists')
    op.drop_table('vocabulary_lists')
    # ### end Alembic commands ###
