"""add translation column to markedword

Revision ID: a024f74ac2b2
Revises: 880b83a291cf
Create Date: 2025-12-22 09:52:58.448049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a024f74ac2b2'
down_revision: Union[str, Sequence[str], None] = '880b83a291cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marked_words', sa.Column('translation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marked_words', 'translation')
    # ### end Alembic commands ###
